#!/usr/bin/env bash
#Change your home IP
# Start the Docker container for DNS server (based on BIND)
docker run -d --restart=always --name=dns-server -p 53:53/udp --cap-add=NET_ADMIN andyshinn/dnsmasq:2.78

# Configure DNS resolution
sudo sed -i '/^nameserver/ d' /etc/resolv.conf
echo "nameserver 127.0.0.2" | sudo tee -a /etc/resolv.conf

# Add custom DNS resolution for facebook.com
sudo sed -i '/^address=\/facebook.com/ d' /etc/dnsmasq.d/02-custom-dns.conf
echo "address=/facebook.com/8.8.8.8" | sudo tee -a /etc/dnsmasq.d/02-custom-dns.conf

# Restart the DNS server
docker restart dns-server